/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Combo;
import io.swagger.model.Pedido;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-03-09T15:05:13.892Z[GMT]")
@Api(value = "combo", description = "the combo API")
@RequestMapping(value="/combo")
public interface ComboApi {

    @ApiOperation(value = "busca un combo", nickname = "buscarCombo", notes = "con un id especifico busca el combo ", response = Combo.class, responseContainer = "Object", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "se obtiene un resultado exitoso en la busqueda", response = Combo.class, responseContainer = "Object"),
        @ApiResponse(code = 400, message = "parametro de busqueda incorrecto") })
    @RequestMapping(value = "/{idCombo}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Combo> buscarCombo(@ApiParam(value = "ingresar el id especifico del combo",required=true) @PathVariable("idCombo") String idCombo);


    @ApiOperation(value = "reemplaza el combo", nickname = "reemplazarCombo", notes = "reemplaza un combo", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "pedido creado"),
        @ApiResponse(code = 400, message = "objeto invalido"),
        @ApiResponse(code = 409, message = "el objeto ya existe") })
    @RequestMapping(value = "/{idCombo}",
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> reemplazarCombo(@ApiParam(value = "ingresar el id especifico del combo",required=true) @PathVariable("idCombo") String idCombo,@ApiParam(value = "Agrega un nuevo pedido"  )  @Valid @RequestBody Combo body);

}
