/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.5).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Combo;
import io.swagger.model.Pedido;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-03-09T15:05:13.892Z[GMT]")
@Api(value = "pedido", description = "the pedido API")
@RequestMapping(value = "/pedido")
public interface PedidoApi {

    @ApiOperation(value = "busca un pedido", nickname = "buscarPedido", notes = "con un id especifico encuentra la representacion del recurso pedido ", response = Pedido.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "se obtiene un resultado exitoso en la busqueda", response = Pedido.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "parametro de busqueda incorrecto") })
    @RequestMapping(
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Pedido>> buscarPedido(@ApiParam(value = "ingresar el id especifico del pedido") @Valid @RequestParam(value = "idPedido", required = false) String idPedido);


    @ApiOperation(value = "crea un pedido", nickname = "crearPedido", notes = "crea un recurso nuevo al arreglo de pedidos", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "pedido creado"),
        @ApiResponse(code = 400, message = "objeto invalido"),
        @ApiResponse(code = 409, message = "el objeto ya existe") })
    @RequestMapping(
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> crearPedido(@ApiParam(value = "Agrega un nuevo pedido"  )  @Valid @RequestBody Pedido body);

    @ApiOperation(value = "busca los combos de un pedido", nickname = "consultarCombosPedido", notes = "con un id especifico encuentra los combos de un pedido ", response = Combo.class, responseContainer = "List", tags={  })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "se obtiene un resultado exitoso en la busqueda", response = Pedido.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "parametro de busqueda incorrecto") })
    @RequestMapping(value="/{idPedido}/combos",
                    produces = { "application/json" },
                    method = RequestMethod.GET)
    List<Combo> consultarCombosPedido(@ApiParam(value= "id del pedido") @PathVariable("idPedido") String idPedido);

}
